[project]
name = "tdd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.7",
    "gunicorn>=23.0.0",
    "lxml[cssselect]>=6.0.2",
    "selenium>=4.38.0",
    "whitenoise>=6.11.0",
]
